/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.com.studywithus;

import static org.junit.Assert.*;
import org.junit.Test;
import main.java.com.studywithus.App;

public class AppTest {
  @Test public void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
